// All US states (+ DC) for programmatic location landing pages.
// slug = URL segment, code = 2-letter, mainCity = largest city, majorCities = served metros.
export interface StateInfo {
    slug: string;
    code: string;
    name: string;
    mainCity: string;
    majorCities: string[];
    /** Unique, locally-specific intro written by the Producer. Rendered in place of the
     *  generic templated intro when present — this is how state pages get de-thinned. */
    intro?: string;
}

// Unique Producer-written intros, keyed by state code. Add entries to enrich more states.
export const STATE_INTRO: Record<string, string> = {
    AL: "Alabama runs on a punishing mix of subtropical heat, soupy Gulf humidity, and a tornado season that puts the state squarely in Dixie Alley. That climate is hard on a home: Mobile sits in the path of Gulf hurricanes and salt air that corrodes panels and roof flashing, while Birmingham and Huntsville endure spring storm fronts that strip shingles and knock out power for days. Year-round humidity forces HVAC systems to run long and hard, and acidic, mineral-heavy water chews through pipes and water heaters across the Black Belt and Tennessee Valley. Our crews understand wind-rated roofing, surge-protected electrical, and cooling sized for real Southern summers, not a spec sheet.",
    AK: "Alaska asks more of a building than almost anywhere on the continent: subarctic cold that drops well below zero, permafrost that heaves and shifts foundations, and winter nights so long that solar arrays have to be sized for a sun that barely clears the horizon. In Fairbanks, deep freezes can split supply lines and force heating systems to run for months without a break, so plumbing has to be insulated and heat-traced and HVAC has to be sized for survival, not comfort. Anchorage sits in a serious seismic zone, where electrical panels, water heaters, and gas lines need bracing most Lower-48 codes never contemplate. Add the wet, salt-laden air around Juneau that corrodes wiring and chews through roofing, and you need crews who understand how this terrain actually behaves. We build and service for those conditions head-on.",
    AR: "Arkansas weather doesn't ease into anything: summers in the Delta around Jonesboro turn thick and swampy, pushing heat indexes past 100 and forcing AC systems to run nearly nonstop, while spring drops the state squarely in Dixie Alley, where tornadoes and straight-line winds peel roofs off homes from Little Rock to Fort Smith. The Ozark hills above Fayetteville add their own twist, with rocky terrain, well water heavy on minerals, and aging housing stock that taxes both plumbing and panels never sized for modern loads. Hard water scales pipes and water heaters fast, humidity rots fascia and feeds mold behind walls, and that constant cooling demand wears HVAC compressors thin. Our crews work all of it, so your electrical, plumbing, HVAC, and roofing hold up to whatever the season throws.",
    CT: "Connecticut weather swings hard: humid summers that punish AC compressors, nor'easters that pile heavy wet snow onto roofs, and a long freeze-thaw season that splits supply lines and heaves foundations from Hartford to the shoreline. Along the coast in Bridgeport, New Haven, and Stamford, salt air corrodes panels, condenser coils, and roof flashing faster than most homeowners expect. The state's housing stock skews old, so cloth-era wiring and undersized service panels turn a simple kitchen remodel into a code-compliance project. Our crews know how Connecticut's hard water scales water heaters and how Long Island Sound storms test every shingle, and we plan our electrical, plumbing, HVAC, and roofing work around exactly that.",
    DE: "Delaware sits low and wet at the edge of the Atlantic, where coastal humidity, nor'easters, and the occasional brushed-by hurricane put homes through a relentless cycle of damp, wind, and salt air. That moisture rots roof decking and warps siding, while the region's notoriously hard, mineral-heavy groundwater scales up water heaters and clogs pipes from Wilmington to Dover. Humid summers run AC systems hard for months, and Newark's older brick rowhomes and Middletown's fast-built new construction each bring their own electrical and ductwork headaches. Our crews know how salt corrosion eats panels and fittings, how to size HVAC for First State humidity, and how to keep a roof watertight through every storm season.",
    DC: "Washington sits in a swampy Potomac basin where summers turn thick with humidity and heat, winters swing through punishing freeze-thaw cycles, and the remnants of Atlantic tropical storms regularly dump flooding rain on the District. That climate is hard on homes: HVAC systems run wide open through muggy July afternoons, while aging cast-iron and galvanized plumbing in the city's rowhouses corrodes and bursts when temperatures crash. Much of Washington's housing stock is historic, brick, and over a century old, which means dated knob-and-tube wiring and undersized electrical panels that were never built for modern loads. Our crews know how to update these homes without gutting their character, whether that's a panel upgrade in Capitol Hill or a roof and gutter system that can actually handle a Mid-Atlantic downpour.",
    GA: "Georgia's swampy, subtropical humidity is the real enemy: months of 90-degree heat and soaking dew points push HVAC systems to their limit and breed the mold and rot that quietly eat at framing and ductwork. Add the afternoon thunderstorms and remnant tropical systems that roll up from the Gulf, and you get power surges that fry panels plus roofs peeled by straight-line winds. Our crews know Atlanta's sprawling subdivisions run on undersized electrical service, that Savannah's salt air and aging coastal homes corrode plumbing and fixtures fast, and that Augusta's red-clay soil shifts foundations under the slab. We size HVAC, harden roofing, and rewire for the way Georgia actually lives.",
    HI: "Island living means salt air that corrodes electrical panels and condenser coils faster than almost anywhere on the mainland, relentless humidity that breeds mold inside walls, and a hurricane season that demands roofs rated to withstand serious wind. In Honolulu, older plantation-era and post-war homes hide outdated wiring and galvanized plumbing that the trades, salt, and time have all worn thin. Hilo's heavy windward rainfall punishes flashing and gutters, while Kailua's coastal exposure eats through fixtures and HVAC systems left unprotected. Our crews understand how to spec corrosion-resistant materials, size solar for year-round sun, and seal a home against moisture before it ever becomes a problem.",
    ID: "Idaho runs to extremes: high-desert summers that bake the Treasure Valley well past 100 degrees, then sub-zero winter nights that swing the freeze-thaw cycle hard enough to split supply lines and heave foundations. Boise and Meridian homes battle some of the hardest, most mineral-laden water in the West, scaling up water heaters and clogging fixtures years before their time, while Nampa's older housing stock often runs on undersized panels never meant for today's heat pumps and EV chargers. Out on the colder Snake River Plain, Idaho Falls demands HVAC that can heat through a deep freeze and cool through dry-summer wildfire smoke without missing a beat. Our crews know how that mineral water wrecks plumbing, how those temperature swings strain electrical and roofing, and they build for both.",
    IL: "Illinois weather doesn't ease into anything. Chicago and Aurora homes endure brutal lake-effect winters with sub-zero polar vortex snaps that burst pipes and bury HVAC systems under heating demand, then pivot to humid, storm-soaked summers where derechos and tornado-grade winds peel back shingles across the prairie. Hard groundwater scales pipes and water heaters statewide, while Rockford's older housing stock and Naperville's deep basements turn sump-pump failures and aging electrical panels into emergencies the moment a spring storm knocks out power. Add freeze-thaw cycles that heave concrete and crack foundations, and you need crews who understand how plumbing, electrical, HVAC, and roofing all take a beating here at once.",
    IN: "Indiana sits squarely in the path of severe Midwest weather: spring and summer storms that spawn tornadoes and straight-line winds, heavy snow and ice loads come January, and a humid continental swing from sticky 90-degree heat to deep below-freezing cold that punishes every system in a house. Around Indianapolis and Carmel, that swing forces HVAC equipment to work both extremes, while older Fort Wayne and Evansville homes often hide knob-and-tube wiring and undersized panels never meant for modern loads. Hard limestone-belt water scales pipes and shortens water-heater life across the state. Our crews handle the roofing, electrical, plumbing, and HVAC work these conditions demand, built for Hoosier homes and the seasons that test them.",
    IA: "Iowa weather doesn't ease into anything: severe summer thunderstorms and derechos roll across the open prairie with straight-line winds that strip shingles and snap service lines, while winter drives sub-zero cold deep enough to freeze and burst unprotected pipes. Add some of the hardest, most mineral-heavy well and municipal water in the Midwest, and homes from Des Moines to Cedar Rapids to Sioux City fight scale that chokes water heaters and shortens fixture life. Our crews understand that a Davenport roof needs to shed hail and 70 mph gusts while the plumbing below it survives a polar swing. We size HVAC for 95-degree humidity and minus-20 nights alike, and we wire and re-pipe with that whole range in mind.",
    KS: "Kansas sits dead center in Tornado Alley, where spring supercells spin up EF-scale twisters and drive softball-sized hail straight into asphalt shingles across Wichita and Topeka. Summers push triple digits with brutal humidity, then winters swing to ice storms and hard freezes that split supply lines and overwork compressors the same season. The water runs notoriously hard here, scaling water heaters and clogging fixtures from Olathe to Overland Park long before their time. Our crews sized HVAC for that whiplash between 105-degree heat and below-zero cold, reroof storm-battered homes with impact-rated materials, and re-pipe around the mineral buildup that quietly wrecks Kansas plumbing. We build for the plains, not a brochure.",
    KY: "Kentucky sits in a humid, storm-prone stretch of the Ohio Valley where summer heat and relentless moisture push HVAC systems hard and breed mold inside walls, while the state's notorious hard, mineral-heavy water quietly scales pipes and shortens water-heater life from Louisville to Owensboro. Spring and fall bring severe thunderstorms and tornado outbreaks that tear at shingles and knock out power across Lexington and Bowling Green, making storm-ready roofing and reliable electrical work less a luxury than a necessity. Add a deep stock of older brick homes with aging wiring and original plumbing, and the maintenance list grows fast. Our crews understand Kentucky's swings between sticky summers and icy winters, and we build every job to hold up to them.",
    LA: "Few states test a home like Louisiana, where subtropical humidity hangs heavy nine months a year, Gulf hurricanes drive storm surge inland, and water tables sit so high that slab foundations shift and pipes corrode faster than crews up north ever see. In New Orleans, century-old shotgun houses and raised cottages demand wiring and ductwork that respect their bones, while Baton Rouge and Lafayette battle relentless heat that runs AC compressors hard from spring through fall. That moisture punishes everything: HVAC systems fight mold and condensate, plumbing fends off mineral-heavy water, and roofs take a beating from wind-driven rain. Our crews understand Louisiana's climate because they work in it every day.",
    ME: "Maine winters are a different animal: subzero stretches, heavy Nor'easter snow loads pressing down on steep roofs, and a deep freeze-thaw cycle that heaves foundations and bursts pipes from Bangor to the coast. Add salt air off the Atlantic that corrodes outdoor electrical panels and condenser units, and you've got conditions that punish anything built or installed without local know-how. Around Portland, Lewiston, and Auburn, much of the housing stock is older—century-plus farmhouses and tightly packed New England triple-deckers with knob-and-tube wiring, undersized heating, and well water hard enough to scale up a water heater fast. Our crews understand how cold, salt, and aging systems collide here, whether you need a furnace that holds through a January cold snap, a roof that sheds spring melt, or wiring brought safely up to code.",
    MD: "Maryland packs an unusual range of punishment into one small state: muggy Mid-Atlantic summers that run air conditioners ragged, Nor'easters and the tail ends of Atlantic hurricanes that drive rain under shingles, and a freeze-thaw winter that swells and cracks aging pipes. Add naturally hard, mineral-heavy water and a housing stock full of century-old Baltimore rowhomes, and the maintenance list gets long fast. Our crews know how Frederick's humidity overworks HVAC compressors, why Silver Spring's older panels strain under modern electrical loads, and how Columbia roofs take a beating from summer storms. We size systems for this climate, not a brochure, and build for the homes Marylanders actually live in.",
    MA: "Massachusetts homes take a beating most of the country never sees: nor'easters that dump heavy, wet snow onto roofs, an unforgiving freeze-thaw cycle that splits pipes and heaves foundations, and salt air off the Atlantic that corrodes everything from panel boxes to flashing. Add a housing stock full of century-old triple-deckers and Colonials in Boston, Cambridge, and Worcester, and you get knob-and-tube wiring, undersized service panels, and steam-heat systems begging to be modernized. Our crews understand how plaster walls, balloon framing, and tight historic-district rules shape every electrical upgrade and HVAC retrofit here. From ice-dam-prone roofs in Springfield to corroded supply lines near the coast, we build for New England's real conditions, not a generic playbook.",
    MI: "Michigan winters arrive off the Great Lakes and don't let go: lake-effect snow piles heavy loads on rooftops, sub-zero stretches freeze and burst supply lines, and the relentless freeze-thaw heaves foundations and chews up shingles across the state. Detroit's dense stock of century-old brick homes hides knob-and-tube wiring and undersized panels that strain under modern furnaces and EV chargers, while hard, mineral-heavy well and municipal water in Grand Rapids and Lansing scales up water heaters and corrodes plumbing from the inside. Our crews know how to size HVAC for humid summers and brutal winters alike, re-roof for snow load, and rewire old homes safely. From Ann Arbor's historic neighborhoods to the suburbs, we build for Michigan's extremes.",
    MN: "Minnesota winters don't negotiate: subzero stretches in Minneapolis and St. Paul push furnaces to their limit, freeze pipes inside exterior walls, and load roofs with heavy snow and the ice dams that follow every thaw. Up in Duluth, lake-effect snow and brutal wind chill add another layer of strain, while ice dams back meltwater under shingles and stain ceilings below. Hard water across much of the state chews through water heaters and fixtures, and aging knob-and-tube and undersized panels in older Rochester and Twin Cities homes can't handle today's electrical demand. Our crews understand how 10,000-lake humidity and a long heating season change the math on HVAC, plumbing, and roofing alike.",
    MS: "Mississippi runs on heat and water: a long subtropical summer where dew points sit in the 70s for months, Gulf moisture that warps doors and feeds mold, and a coast that takes the brunt of Atlantic hurricanes head-on. In Biloxi and Gulfport, salt air corrodes panels and roof fasteners while storm surge tests every flashing seam, so our roofing and electrical crews build for wind uplift and saltwater the way locals expect. Push inland to Hattiesburg and Jackson and the fight shifts to relentless humidity that overworks HVAC systems and hard, mineral-heavy groundwater that scales up water heaters and plumbing lines. Yazoo clay that swells and shrinks underfoot only adds to the strain on slabs and pipes. We size, seal, and install for that reality, not a brochure.",
    MO: "Missouri sits squarely in the middle of Tornado Alley's eastern edge, where violent spring storms, baseball-sized hail, and straight-line winds tear at roofs from Kansas City to St. Louis every season. The state swings hard between brutal humid summers that push HVAC systems to their limits and ice storms that snap power lines and freeze pipes overnight. Hard, mineral-heavy water across much of the state scales up water heaters and corrodes plumbing fixtures faster than homeowners expect. Older brick homes in St. Louis and Columbia often hide knob-and-tube or undersized panels that can't handle modern loads, while Springfield's storm season keeps roofers and electricians busy long after the clouds clear. Our crews understand these conditions because we work in them.",
    MT: "Montana punishes a home in ways the rest of the country rarely sees: subzero Continental Divide winters that can swing 50 degrees in a day, deep snow loads pressing down on roofs from Bozeman to Great Falls, and bone-dry summers that turn the western valleys into wildfire country. That freeze-thaw whiplash splits supply lines and stresses water heaters, which is why our plumbing and HVAC crews build for heating systems that have to claw through January, not coast through it. In Missoula, smoke-season air pushes homeowners toward sealed envelopes and serious filtration, while Billings roofs need fasteners and underlayment rated for wind, ice dams, and snow that lingers for months. We size, wire, and weatherproof for the real Montana, not a milder version of it.",
    NE: "Nebraska sits in the heart of Tornado Alley, where supercells and straight-line winds can strip shingles off a roof in a single afternoon and the swing from sub-zero January nights to 100-degree July humidity pushes HVAC systems to their limit. Homes in Omaha and Lincoln battle some of the hardest water in the country, the kind that scales up water heaters and chokes plumbing lines years before their time. Out in Grand Island and Bellevue, older housing stock often hides aluminum wiring and undersized panels never meant to carry today's central air and EV chargers. Our crews know that a Nebraska roof has to shed hail and survive wind, that pipes need protection against deep frost lines, and that electrical work has to hold up when the next storm rolls across the plains. We build for the weather this state actually throws at us.",
    NV: "Nevada runs your home harder than almost anywhere else: a high-desert climate where Las Vegas and Henderson routinely push past 110 degrees in summer, mineral-heavy hard water that scales pipes and shortens water heater life, and a northern swing around Reno and Sparks that swaps triple-digit heat for real winter freezes at altitude. That punishing sun and brutal AC load make HVAC sizing and electrical capacity non-negotiable, while the same relentless rays make Nevada one of the best solar states in the country if the panels and wiring are done right. Hard water quietly eats plumbing fixtures and tankless units long before anyone notices. Our crews understand the desert because they work in it every day.",
    NH: "New Hampshire homes take a beating that few realize: nor'easters dump heavy, wet snow that piles onto roofs and overwhelms ice dams, while January nights regularly plunge below zero and crack supply lines in older Manchester and Nashua housing stock. Add granite-state well water that runs hard and acidic, chewing through copper pipe and water heaters across Concord and Dover, plus a short, humid summer that makes right-sized HVAC tricky. Our crews understand snow-load roofing, freeze-resistant plumbing reroutes, whole-home water treatment, and heat pumps tuned for deep New England cold. From historic Colonials to newer builds, we wire, plumb, and seal them for the climate they actually live in.",
    NJ: "New Jersey runs the gauntlet from salt-laced coastal air along the Shore to dense, century-old row houses packed into Newark, Jersey City, and Paterson, and the building stress shows in every trade. Nor'easters and coastal flooding push water into basements and corrode outdoor electrical service, while humid summers and hard-freezing winters force HVAC systems to swing from heavy cooling to heating loads within the same week. The aging housing stock hides knob-and-tube wiring, undersized panels, and galvanized plumbing that no longer keeps up with modern demand. Hard water scales fixtures and water heaters across the region, and salt-driven roof and gutter wear means coastal homes need flashing and shingles that can take the abuse. Our crews understand these conditions and build for them.",
    NM: "New Mexico runs on extremes: high-desert sun that bakes Albuquerque rooftops 300-plus days a year, a mile-high-and-then-some elevation that thins the air your furnace burns, and some of the hardest, most mineral-heavy water in the Southwest scaling up pipes and water heaters statewide. Add monsoon downpours that hammer flat roofs every summer and bone-dry winters that swing 40 degrees between noon and midnight, and the demands on a home stack up fast. Santa Fe's historic adobe and viga construction needs electrical and HVAC work that respects old bones, while booming Rio Rancho and Las Cruces subdivisions are prime ground for solar that actually pays off in this much sun. Our crews know how that high-desert mix wears on plumbing, roofing, and everything in between.",
    NC: "North Carolina spans three worlds in a single state: the salt air and hurricane swells that hammer the coast, the muggy Piedmont summers around Charlotte, Raleigh, and Greensboro that run heat pumps and central AC nonstop, and the Appalachian foothills where winter still bites. That relentless humidity breeds mold, swells crawlspace framing, and forces HVAC systems to fight moisture as hard as heat, while remnants of tropical storms tear shingles loose and flood basements faster than a sump pump can keep up. Hard groundwater corrodes plumbing and chokes water heaters, and aging brick-and-frame homes often hide undersized panels never meant for today's loads. Our crews know which problems each region throws at a house, and we build every fix for it.",
    ND: "Few states swing as hard as North Dakota, where winters drop to forty below and summers spike past one hundred, forcing furnaces and air conditioners to work at opposite extremes within the same year. That cold is no joke for homes in Fargo and Grand Forks, where deep frost lines push pipes below eight feet and a single freeze can split a supply line or heave a foundation overnight. Bismarck sits in some of the gustiest country in the nation, so wind-driven snow and prairie storms beat hard on shingles and seams, while iron-heavy well and city water scales up fixtures and water heaters fast. Our crews size HVAC for both halves of that 140-degree range, harden plumbing against frost, and install roofing built to take the wind. We work where the weather punishes shortcuts.",
    OH: "Ohio sits squarely in the path of Great Lakes moisture and Gulf air colliding, which means freeze-thaw winters that heave foundations and split supply lines, humid summers that overwork every compressor, and a tornado-and-windstorm season that strips shingles off roofs from Toledo to Cincinnati. Cleveland's lake-effect snow piles load onto aging roofs while road salt and damp basements quietly eat at electrical panels and water heaters. Much of Columbus and the older river-town neighborhoods run on housing stock built decades ago, with knob-and-tube wiring and galvanized plumbing that were never meant for today's loads. Our crews understand how this climate punishes HVAC systems and how hard water scales up pipes across the state. We size, wire, and seal for Ohio conditions, not a generic spec sheet.",
    OK: "Few states sit deeper in Tornado Alley than Oklahoma, where spring supercells spawn EF-grade twisters and the hail that comes with them shreds shingles across Oklahoma City and Norman year after year. Summers push past 100 degrees with brutal humidity that runs HVAC systems ragged, while January ice storms snap power lines and leave Edmond homes dark for days. The region's notoriously hard, mineral-heavy water scales up plumbing and water heaters faster than most owners expect, and expansive red clay soil shifts foundations under older Tulsa neighborhoods. Our crews know what storm-rated roofing, surge-protected electrical, and right-sized AC actually take to survive an Oklahoma year. We build for this climate, not a brochure.",
    OR: "Oregon throws two climates at a single house: the wet, mossy Willamette Valley west of the Cascades, where Portland, Salem, and Eugene soak through eight months of rain that rots roof decking, clogs gutters, and breeds the mildew our roofing and remodeling crews fight year-round. Cross the mountains to Bend, and the high desert flips the script with freezing winters, bone-dry summers, and a thin alpine sun that's earned the eastern half its solar boom. Add aging Craftsman and bungalow stock with knob-and-tube wiring and undersized panels, plus a tightening wildfire-defense code, and you've got electrical and HVAC work that demands crews who actually understand this state's split personality. We build for both sides of the Cascades.",
    PA: "Pennsylvania weather doesn't pick a lane, and your home pays for it: lake-effect snow that buries Erie under feet of it, humid summers that push HVAC systems to their limit in Philadelphia, and a relentless freeze-thaw cycle that heaves foundations and splits pipes across Pittsburgh's hills. Add some of the oldest housing stock in the country, where rowhomes and century-old colonials still run knob-and-tube wiring and undersized panels that were never meant for modern loads. Heavy wet snow loads test aging roofs every winter, while hard water chews through plumbing and water heaters statewide. We build crews who know these conditions cold, from re-piping a Pittsburgh basement to rewiring an Allentown rowhome the right way.",
    RI: "Rhode Island packs more coastline per square mile than almost anywhere in the country, and that salt air is relentless on the Ocean State's housing stock. In Newport and along Narragansett Bay, sea-spray corrosion eats through outdoor electrical panels, condenser coils, and roof flashing years faster than inland gear, while hurricane and nor'easter season tests every shingle. Inland, Providence and Cranston are full of dense Colonial-era and triple-decker homes where original knob-and-tube wiring and undersized service still lurk behind plaster. Add humid summers that overwork undersized AC and hard New England water that scales up pipes and water heaters, and you need crews who know how the climate actually treats a house. We build for it from electrical and HVAC to roofing and plumbing.",
    SC: "South Carolina weather doesn't ask permission: subtropical humidity that swells wood and feeds mold, hurricane season pushing storm surge and salt air up the coast, and summer heat indexes that run AC compressors ragged for months. In Charleston and Mount Pleasant, briny air corrodes electrical panels, outdoor disconnects, and condenser coils faster than inland gear ever sees, while the Lowcountry's high water table and historic homes hide aging plumbing and undersized service. Push into Columbia and Greenville and the load shifts to flood-prone slabs, hard water scaling fixtures, and roofs that take a beating from severe thunderstorms and the occasional ice event. Our crews know how each one fails, and how to build for it.",
    SD: "South Dakota throws a full continental gauntlet at a house: subzero January cold and heavy prairie snow load on the eastern side near Sioux Falls and Brookings, then bone-dry summer heat and Black Hills wildfire risk out around Rapid City. Add some of the hardest, most mineral-loaded groundwater in the country and you get scale-choked water heaters and clogged fixtures that wear plumbing out years early. The same swings hammer HVAC systems that have to swing from deep-freeze heating to triple-digit cooling, and they punish roofs caught under spring hail and high plains wind. Our crews understand frost-depth pipe runs, water-treatment for hard water, and heating built for genuine Dakota winters.",
    TN: "Tennessee weather doesn't ease up on a house. Summers turn thick with Gulf humidity that overworks HVAC systems and breeds mold in attics and crawlspaces from Memphis to Nashville, while the state sits squarely in Dixie Alley, where spring tornadoes and straight-line winds tear shingles off roofs across Middle Tennessee. The hard, mineral-heavy water common around Knoxville and Chattanooga scales up water heaters and chews through plumbing fixtures faster than most owners expect. Add aging electrical panels in century-old homes near the rivers, and you need crews who understand how this region actually behaves. Ours plan for the heat, the storms, and the hard water from day one.",
    UT: "Utah's high-desert climate runs to extremes: thin Wasatch Front air above 4,000 feet, brutal summer heat baking the Salt Lake Valley, heavy mountain snow load piling onto roofs, and some of the hardest water in the country scaling up pipes and water heaters across the region. Homes in Salt Lake City, West Valley City, and Provo deal with sharp freeze-thaw swings that stress plumbing and crack foundations, while bone-dry inversions push HVAC systems hard from July through January. That hard water shortens the life of fixtures and tank heaters, and intense year-round sun makes Utah rooftops prime territory for solar. Our crews understand how altitude, mineral buildup, and snow loads actually behave here, so the electrical, plumbing, HVAC, and roofing work holds up to real Utah conditions.",
    VT: "Vermont homes get tested in ways flatland states never see: sub-zero Green Mountain winters that pile heavy snow onto steep roofs, a freeze-thaw cycle that heaves foundations and bursts pipes, and a housing stock full of century-old farmhouses with knob-and-tube wiring and undersized panels. Around Burlington and South Burlington, that means heating systems and heat pumps working overtime through long, damp shoulder seasons, while older Rutland and Essex homes often need electrical upgrades before they can carry modern loads. Our crews understand mountain snow load, mud-season grading, and the quirks of historic timber framing. From boiler swaps and panel rebuilds to roofing built to shed Vermont winters, we work to the conditions on the ground.",
    VA: "Virginia puts a home through every season in a single year: muggy Tidewater summers that run AC units ragged in Virginia Beach and Norfolk, ice storms and freeze-thaw swings that split pipes inland, and the salt air off the Chesapeake that corrodes panels, fittings, and roof flashing faster than any inland climate. Hurricane and nor'easter remnants drive wind-driven rain under shingles from the coast to Richmond, while Northern Virginia's older Arlington housing stock often hides undersized electrical service and aging ductwork behind charming brick. Our crews size HVAC for that coastal humidity, harden plumbing against hard water and hard freezes, and seal roofs to take the wind. We work the whole state, from the Bay to the Blue Ridge.",
    WA: "Washington is really two climates fighting under one roof: the wet, mild marine air west of the Cascades and the dry, hard-freezing high desert to the east. In Seattle, Tacoma, and Bellevue, near-constant rain and damp winters punish roofs with moss and rot, push moisture into walls, and keep heat pumps running through gray, low-sun months that solar has to work hard to offset. Cross into Spokane and the equation flips to sub-zero snaps that split supply lines and tax aging furnaces. Add some of the softest water in the country on the coast and mineral-heavy wells inland, and plumbing, HVAC, and roofing all have to be sized for the side of the mountains you're actually standing on. Our crews build for both.",
    WV: "West Virginia sits almost entirely inside the Appalachian Mountains, where steep hollows, narrow ridgelines, and a humid continental climate put homes through wringers most states never see. Heavy winter snow load presses down on roofs in Morgantown and the high country, while the Kanawha and Ohio valleys around Charleston and Parkersburg trap summer humidity that overworks HVAC systems and breeds the moisture that warps framing and corrodes wiring. Older coal-era and river-town housing stock in Huntington often hides knob-and-tube circuits and galvanized supply lines that crack under hard, mineral-heavy water. Our crews understand mountain elevation changes, freeze-thaw on hillside foundations, and how flood-prone bottomland affects electrical panels and plumbing. From roof reinforcement to repipes and panel upgrades, we build for the terrain West Virginians actually live on.",
    WI: "Wisconsin homes take a beating few states understand: lake-effect snow loads off Lake Michigan that pile onto Green Bay and Milwaukee roofs, sub-zero polar stretches that freeze and burst supply lines, and a brutal freeze-thaw swing that heaves foundations and chews up shingles. Add some of the hardest water in the Midwest, and water heaters and fixtures in Madison and Kenosha scale up and fail years early. That climate punishes the wrong HVAC sizing fast, so our crews spec heating systems for real January nights, not catalog averages. We reinforce and flash roofs for heavy snow and ice dams, repipe around hard-water damage, and wire homes to carry the load when the furnace runs for days straight.",
    WY: "Wyoming punishes anything built halfway: relentless wind that tears at ridgelines and shingles, sub-zero winter nights that freeze pipes solid, and a high-plains altitude that throws off furnace combustion and heat-pump performance. In Cheyenne and Casper, that wind drives ice dams and rips at roof flashing, while Laramie's brutal cold and thin air mean an undersized HVAC system simply can't keep up. Hard, mineral-heavy well water quietly scales water heaters and corrodes fixtures across the basin. Our crews size equipment for elevation, anchor roofing for gusts that would peel a coastal house apart, and build plumbing and electrical that holds through a Wyoming winter, not just a mild one.",
    CO: "Colorado homes face challenges few other states do: 5,280-foot altitude that changes how furnaces combust and ACs perform, a brutal freeze-thaw cycle that cracks pipes and concrete, and some of the worst hail in the country battering Front Range roofs every summer. Our crews were built here — we know the knob-and-tube wiring hiding in Capitol Hill Victorians, the expansive clay soils that shift foundations in Aurora, and exactly how to size a furnace for a Denver winter. From the foothills of Golden to the plains of Brighton, we bring licensed, code-compliant work to every Colorado home.",
    TX: "Everything's bigger in Texas — including the demands on your home's systems. Triple-digit summers push AC units to their limit from Houston's gulf humidity to the dry heat of El Paso, while sudden cold snaps (remember Winter Storm Uri?) expose underbuilt plumbing and electrical. Our Texas crews handle it all: high-capacity HVAC built for relentless cooling loads, freeze-resilient pipe protection, panel upgrades for sprawling new-builds in Austin and Dallas, and storm-ready roofing across Tornado Alley.",
    CA: "California's range of climates — coastal fog in San Francisco, desert heat in the Inland Empire, wildfire-prone foothills — means no two homes have the same needs. We deliver Title 24-compliant electrical, high-efficiency HVAC, and one of the strongest solar markets in the nation (stacking federal credits with California incentives), plus seismic-aware plumbing and roofing from Los Angeles to Sacramento.",
    FL: "Florida living is hard on a home: relentless humidity, salt air along both coasts, and a hurricane season that tests every roof and panel from Jacksonville to Miami. Our Florida crews specialize in moisture-resilient HVAC and indoor air quality, hurricane-rated roofing and repairs, surge-protected electrical, and the kind of fast emergency response you need when a storm rolls through.",
    NY: "From pre-war walk-ups in New York City to lake-effect snow country in Buffalo, New York homes span a century of building styles and a punishing range of weather. We modernize aging electrical and knob-and-tube wiring, install heating systems that hold up to Northeast winters, and handle plumbing, roofing and remodeling across the Empire State — permits and co-op boards included.",
    AZ: "Arizona's extreme heat is unforgiving on home systems — AC isn't a luxury here, it's survival, and a failed unit in a Phoenix July is an emergency. Our Arizona crews build for it: high-capacity cooling, sun-hardened roofing, electrical sized for heavy AC and EV loads, and rooftop solar that turns 300+ days of sunshine into real savings from Tucson to Scottsdale.",
};


export const STATES: StateInfo[] = [
    { slug: 'alabama', code: 'AL', name: 'Alabama', mainCity: 'Birmingham', majorCities: ['Birmingham', 'Montgomery', 'Huntsville', 'Mobile', 'Tuscaloosa'] },
    { slug: 'alaska', code: 'AK', name: 'Alaska', mainCity: 'Anchorage', majorCities: ['Anchorage', 'Fairbanks', 'Juneau', 'Wasilla', 'Sitka'] },
    { slug: 'arizona', code: 'AZ', name: 'Arizona', mainCity: 'Phoenix', majorCities: ['Phoenix', 'Tucson', 'Mesa', 'Chandler', 'Scottsdale', 'Glendale'] },
    { slug: 'arkansas', code: 'AR', name: 'Arkansas', mainCity: 'Little Rock', majorCities: ['Little Rock', 'Fayetteville', 'Fort Smith', 'Springdale', 'Jonesboro'] },
    { slug: 'california', code: 'CA', name: 'California', mainCity: 'Los Angeles', majorCities: ['Los Angeles', 'San Diego', 'San Jose', 'San Francisco', 'Sacramento', 'Fresno'] },
    { slug: 'colorado', code: 'CO', name: 'Colorado', mainCity: 'Denver', majorCities: ['Denver', 'Aurora', 'Colorado Springs', 'Lakewood', 'Fort Collins', 'Boulder'] },
    { slug: 'connecticut', code: 'CT', name: 'Connecticut', mainCity: 'Bridgeport', majorCities: ['Bridgeport', 'New Haven', 'Hartford', 'Stamford', 'Waterbury'] },
    { slug: 'delaware', code: 'DE', name: 'Delaware', mainCity: 'Wilmington', majorCities: ['Wilmington', 'Dover', 'Newark', 'Middletown', 'Bear'] },
    { slug: 'district-of-columbia', code: 'DC', name: 'District of Columbia', mainCity: 'Washington', majorCities: ['Washington'] },
    { slug: 'florida', code: 'FL', name: 'Florida', mainCity: 'Jacksonville', majorCities: ['Jacksonville', 'Miami', 'Tampa', 'Orlando', 'St. Petersburg', 'Fort Lauderdale'] },
    { slug: 'georgia', code: 'GA', name: 'Georgia', mainCity: 'Atlanta', majorCities: ['Atlanta', 'Augusta', 'Savannah', 'Columbus', 'Athens', 'Macon'] },
    { slug: 'hawaii', code: 'HI', name: 'Hawaii', mainCity: 'Honolulu', majorCities: ['Honolulu', 'Hilo', 'Kailua', 'Kapolei', 'Pearl City'] },
    { slug: 'idaho', code: 'ID', name: 'Idaho', mainCity: 'Boise', majorCities: ['Boise', 'Meridian', 'Nampa', 'Idaho Falls', 'Pocatello'] },
    { slug: 'illinois', code: 'IL', name: 'Illinois', mainCity: 'Chicago', majorCities: ['Chicago', 'Aurora', 'Naperville', 'Joliet', 'Rockford', 'Springfield'] },
    { slug: 'indiana', code: 'IN', name: 'Indiana', mainCity: 'Indianapolis', majorCities: ['Indianapolis', 'Fort Wayne', 'Evansville', 'South Bend', 'Carmel'] },
    { slug: 'iowa', code: 'IA', name: 'Iowa', mainCity: 'Des Moines', majorCities: ['Des Moines', 'Cedar Rapids', 'Davenport', 'Sioux City', 'Iowa City'] },
    { slug: 'kansas', code: 'KS', name: 'Kansas', mainCity: 'Wichita', majorCities: ['Wichita', 'Overland Park', 'Kansas City', 'Topeka', 'Olathe'] },
    { slug: 'kentucky', code: 'KY', name: 'Kentucky', mainCity: 'Louisville', majorCities: ['Louisville', 'Lexington', 'Bowling Green', 'Owensboro', 'Covington'] },
    { slug: 'louisiana', code: 'LA', name: 'Louisiana', mainCity: 'New Orleans', majorCities: ['New Orleans', 'Baton Rouge', 'Shreveport', 'Lafayette', 'Lake Charles'] },
    { slug: 'maine', code: 'ME', name: 'Maine', mainCity: 'Portland', majorCities: ['Portland', 'Lewiston', 'Bangor', 'Auburn', 'Biddeford'] },
    { slug: 'maryland', code: 'MD', name: 'Maryland', mainCity: 'Baltimore', majorCities: ['Baltimore', 'Columbia', 'Germantown', 'Silver Spring', 'Frederick'] },
    { slug: 'massachusetts', code: 'MA', name: 'Massachusetts', mainCity: 'Boston', majorCities: ['Boston', 'Worcester', 'Springfield', 'Cambridge', 'Lowell'] },
    { slug: 'michigan', code: 'MI', name: 'Michigan', mainCity: 'Detroit', majorCities: ['Detroit', 'Grand Rapids', 'Warren', 'Sterling Heights', 'Ann Arbor', 'Lansing'] },
    { slug: 'minnesota', code: 'MN', name: 'Minnesota', mainCity: 'Minneapolis', majorCities: ['Minneapolis', 'St. Paul', 'Rochester', 'Duluth', 'Bloomington'] },
    { slug: 'mississippi', code: 'MS', name: 'Mississippi', mainCity: 'Jackson', majorCities: ['Jackson', 'Gulfport', 'Southaven', 'Hattiesburg', 'Biloxi'] },
    { slug: 'missouri', code: 'MO', name: 'Missouri', mainCity: 'Kansas City', majorCities: ['Kansas City', 'St. Louis', 'Springfield', 'Columbia', 'Independence'] },
    { slug: 'montana', code: 'MT', name: 'Montana', mainCity: 'Billings', majorCities: ['Billings', 'Missoula', 'Great Falls', 'Bozeman', 'Helena'] },
    { slug: 'nebraska', code: 'NE', name: 'Nebraska', mainCity: 'Omaha', majorCities: ['Omaha', 'Lincoln', 'Bellevue', 'Grand Island', 'Kearney'] },
    { slug: 'nevada', code: 'NV', name: 'Nevada', mainCity: 'Las Vegas', majorCities: ['Las Vegas', 'Henderson', 'Reno', 'North Las Vegas', 'Sparks'] },
    { slug: 'new-hampshire', code: 'NH', name: 'New Hampshire', mainCity: 'Manchester', majorCities: ['Manchester', 'Nashua', 'Concord', 'Dover', 'Rochester'] },
    { slug: 'new-jersey', code: 'NJ', name: 'New Jersey', mainCity: 'Newark', majorCities: ['Newark', 'Jersey City', 'Paterson', 'Elizabeth', 'Trenton', 'Edison'] },
    { slug: 'new-mexico', code: 'NM', name: 'New Mexico', mainCity: 'Albuquerque', majorCities: ['Albuquerque', 'Las Cruces', 'Rio Rancho', 'Santa Fe', 'Roswell'] },
    { slug: 'new-york', code: 'NY', name: 'New York', mainCity: 'New York City', majorCities: ['New York City', 'Buffalo', 'Rochester', 'Yonkers', 'Syracuse', 'Albany'] },
    { slug: 'north-carolina', code: 'NC', name: 'North Carolina', mainCity: 'Charlotte', majorCities: ['Charlotte', 'Raleigh', 'Greensboro', 'Durham', 'Winston-Salem'] },
    { slug: 'north-dakota', code: 'ND', name: 'North Dakota', mainCity: 'Fargo', majorCities: ['Fargo', 'Bismarck', 'Grand Forks', 'Minot', 'West Fargo'] },
    { slug: 'ohio', code: 'OH', name: 'Ohio', mainCity: 'Columbus', majorCities: ['Columbus', 'Cleveland', 'Cincinnati', 'Toledo', 'Akron', 'Dayton'] },
    { slug: 'oklahoma', code: 'OK', name: 'Oklahoma', mainCity: 'Oklahoma City', majorCities: ['Oklahoma City', 'Tulsa', 'Norman', 'Broken Arrow', 'Edmond'] },
    { slug: 'oregon', code: 'OR', name: 'Oregon', mainCity: 'Portland', majorCities: ['Portland', 'Salem', 'Eugene', 'Gresham', 'Hillsboro', 'Bend'] },
    { slug: 'pennsylvania', code: 'PA', name: 'Pennsylvania', mainCity: 'Philadelphia', majorCities: ['Philadelphia', 'Pittsburgh', 'Allentown', 'Erie', 'Reading'] },
    { slug: 'rhode-island', code: 'RI', name: 'Rhode Island', mainCity: 'Providence', majorCities: ['Providence', 'Warwick', 'Cranston', 'Pawtucket', 'Newport'] },
    { slug: 'south-carolina', code: 'SC', name: 'South Carolina', mainCity: 'Charleston', majorCities: ['Charleston', 'Columbia', 'Greenville', 'Mount Pleasant', 'Rock Hill'] },
    { slug: 'south-dakota', code: 'SD', name: 'South Dakota', mainCity: 'Sioux Falls', majorCities: ['Sioux Falls', 'Rapid City', 'Aberdeen', 'Brookings', 'Watertown'] },
    { slug: 'tennessee', code: 'TN', name: 'Tennessee', mainCity: 'Nashville', majorCities: ['Nashville', 'Memphis', 'Knoxville', 'Chattanooga', 'Clarksville'] },
    { slug: 'texas', code: 'TX', name: 'Texas', mainCity: 'Houston', majorCities: ['Houston', 'San Antonio', 'Dallas', 'Austin', 'Fort Worth', 'El Paso'] },
    { slug: 'utah', code: 'UT', name: 'Utah', mainCity: 'Salt Lake City', majorCities: ['Salt Lake City', 'West Valley City', 'Provo', 'West Jordan', 'Orem'] },
    { slug: 'vermont', code: 'VT', name: 'Vermont', mainCity: 'Burlington', majorCities: ['Burlington', 'Essex', 'South Burlington', 'Colchester', 'Rutland'] },
    { slug: 'virginia', code: 'VA', name: 'Virginia', mainCity: 'Virginia Beach', majorCities: ['Virginia Beach', 'Norfolk', 'Chesapeake', 'Richmond', 'Arlington'] },
    { slug: 'washington', code: 'WA', name: 'Washington', mainCity: 'Seattle', majorCities: ['Seattle', 'Spokane', 'Tacoma', 'Vancouver', 'Bellevue', 'Everett'] },
    { slug: 'west-virginia', code: 'WV', name: 'West Virginia', mainCity: 'Charleston', majorCities: ['Charleston', 'Huntington', 'Morgantown', 'Parkersburg', 'Wheeling'] },
    { slug: 'wisconsin', code: 'WI', name: 'Wisconsin', mainCity: 'Milwaukee', majorCities: ['Milwaukee', 'Madison', 'Green Bay', 'Kenosha', 'Racine', 'Appleton'] },
    { slug: 'wyoming', code: 'WY', name: 'Wyoming', mainCity: 'Cheyenne', majorCities: ['Cheyenne', 'Casper', 'Laramie', 'Gillette', 'Rock Springs'] },
];

/**
 * Rewrite Denver-specific marketing copy for a given state, so the Denver `CATEGORIES`
 * descriptions/FAQs read correctly on nationwide /locations pages. Only for BODY copy —
 * never the brand name "Denver Metro Services" (which is correct on every page).
 */
export function delocalize(text: string, s: StateInfo): string {
    if (!text) return text;
    return text
        .replace(/\bin Denver, Aurora,?\s*(?:&|and)\s*Lakewood\b/gi, `in ${s.name}`)
        .replace(/\bDenver, Aurora,?\s*(?:&|and)\s*Lakewood\b/gi, s.name)
        .replace(/\bDenver\s*(?:&|and)\s*Aurora\b/gi, s.mainCity)
        .replace(/\bthe Denver Metro Area\b/gi, s.name)
        .replace(/\bDenver Metro Area\b/gi, s.name)
        .replace(/\bacross the Metro area\b/gi, `across ${s.name}`)
        .replace(/\bthe Metro area\b/gi, s.name)
        .replace(/\bDenver\b/g, s.mainCity)
        .replace(/\bColorado\b/g, s.name)
        .replace(/\bXcel Energy\b/g, 'your local utility')
        .replace(/\bXcel\b/g, 'local utility');
}

export const STATE_BY_CODE: Record<string, StateInfo> = Object.fromEntries(STATES.map((s) => [s.code, s]));
export const STATE_BY_SLUG: Record<string, StateInfo> = Object.fromEntries(STATES.map((s) => [s.slug, s]));
