// Largest / main city per US state (+ DC). Used by the geolocation greeting banner
// to show the visitor's state's main city. Denver is the real service area.
export const STATE_MAIN_CITY: Record<string, { city: string; name: string }> = {
    AL: { city: 'Birmingham', name: 'Alabama' },
    AK: { city: 'Anchorage', name: 'Alaska' },
    AZ: { city: 'Phoenix', name: 'Arizona' },
    AR: { city: 'Little Rock', name: 'Arkansas' },
    CA: { city: 'Los Angeles', name: 'California' },
    CO: { city: 'Denver', name: 'Colorado' },
    CT: { city: 'Bridgeport', name: 'Connecticut' },
    DE: { city: 'Wilmington', name: 'Delaware' },
    DC: { city: 'Washington', name: 'District of Columbia' },
    FL: { city: 'Jacksonville', name: 'Florida' },
    GA: { city: 'Atlanta', name: 'Georgia' },
    HI: { city: 'Honolulu', name: 'Hawaii' },
    ID: { city: 'Boise', name: 'Idaho' },
    IL: { city: 'Chicago', name: 'Illinois' },
    IN: { city: 'Indianapolis', name: 'Indiana' },
    IA: { city: 'Des Moines', name: 'Iowa' },
    KS: { city: 'Wichita', name: 'Kansas' },
    KY: { city: 'Louisville', name: 'Kentucky' },
    LA: { city: 'New Orleans', name: 'Louisiana' },
    ME: { city: 'Portland', name: 'Maine' },
    MD: { city: 'Baltimore', name: 'Maryland' },
    MA: { city: 'Boston', name: 'Massachusetts' },
    MI: { city: 'Detroit', name: 'Michigan' },
    MN: { city: 'Minneapolis', name: 'Minnesota' },
    MS: { city: 'Jackson', name: 'Mississippi' },
    MO: { city: 'Kansas City', name: 'Missouri' },
    MT: { city: 'Billings', name: 'Montana' },
    NE: { city: 'Omaha', name: 'Nebraska' },
    NV: { city: 'Las Vegas', name: 'Nevada' },
    NH: { city: 'Manchester', name: 'New Hampshire' },
    NJ: { city: 'Newark', name: 'New Jersey' },
    NM: { city: 'Albuquerque', name: 'New Mexico' },
    NY: { city: 'New York City', name: 'New York' },
    NC: { city: 'Charlotte', name: 'North Carolina' },
    ND: { city: 'Fargo', name: 'North Dakota' },
    OH: { city: 'Columbus', name: 'Ohio' },
    OK: { city: 'Oklahoma City', name: 'Oklahoma' },
    OR: { city: 'Portland', name: 'Oregon' },
    PA: { city: 'Philadelphia', name: 'Pennsylvania' },
    RI: { city: 'Providence', name: 'Rhode Island' },
    SC: { city: 'Charleston', name: 'South Carolina' },
    SD: { city: 'Sioux Falls', name: 'South Dakota' },
    TN: { city: 'Nashville', name: 'Tennessee' },
    TX: { city: 'Houston', name: 'Texas' },
    UT: { city: 'Salt Lake City', name: 'Utah' },
    VT: { city: 'Burlington', name: 'Vermont' },
    VA: { city: 'Virginia Beach', name: 'Virginia' },
    WA: { city: 'Seattle', name: 'Washington' },
    WV: { city: 'Charleston', name: 'West Virginia' },
    WI: { city: 'Milwaukee', name: 'Wisconsin' },
    WY: { city: 'Cheyenne', name: 'Wyoming' },
};

// Denver-metro cities the business actually serves (for in-area personalization).
export const SERVED_METRO_CITIES = [
    'Denver', 'Aurora', 'Lakewood', 'Centennial', 'Arvada', 'Thornton', 'Brighton',
    'Highlands Ranch', 'Littleton', 'Westminster', 'Golden', 'Wheat Ridge', 'Englewood',
    'Commerce City', 'Parker', 'Castle Rock', 'Broomfield',
];
